### ISSUE TITLE
[Bug]: Typo in function name

### ISSUE THREAD

**Issue by szepeviktor** [Setono/sylius-order-edit-plugin#30]
### Plugin version

0

### Sylius version

0

### What happened?

https://github.com/search?q=repo%3ASetono%2Fsylius-order-edit-plugin%20Programatically&type=code

it should have two "m"-s
https://www.merriam-webster.com/dictionary/programmatically

**Comment by Zales0123** [comment]
Hello Victor! Thank you for pointing this out, are you willing to open a PR with a required change? Thanks in advance! :)

**Comment by szepeviktor** [comment]
Done 🍏
